version: "3.9"
   
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - '5000:5000'
    environment:
      - POSTGRES_DB=addgraphql_db
      - POSTGRES_USER=addgraphql_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
    volumes:
      - .:/app
  db:
    image: postgres
    environment:
      - POSTGRES_DB=addgraphql_db
      - POSTGRES_USER=addgraphql_user
      - POSTGRES_PASSWORD=password
